### ISSUE TITLE
Build `modi-flows` into conda

### ISSUE THREAD

**Issue by diegoabt** [aleable/MODI#30]
Make it installable from conda.

**Comment by diegoabt** [comment]
There's a conflict between python and numpy. After running `conda skeleton pypi modi-flows`, I get:

```
Best match: numpy 1.26.0b1
Processing numpy-1.26.0b1.tar.gz
Writing /tmp/easy_install-5e3d8jrf/numpy-1.26.0b1/setup.cfg
Running numpy-1.26.0b1/setup.py -q bdist_egg --dist-dir /tmp/easy_install-5e3d8jrf/numpy-1.26.0b1/egg-dist-tmp-wqk44jzf
Traceback (most recent call last):
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5e3d8jrf/numpy-1.26.0b1/setup.py", line 22, in <module>
    #'scikit-umfpack'
RuntimeError: Python version >= 3.9 required.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    setup(
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/dist.py", line 1233, in run_command
    super().run_command(command)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/install.py", line 84, in run
    self.do_egg_install()
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/install.py", line 140, in do_egg_install
    cmd.run(show_deprecation=False)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 442, in run
    self.easy_install(spec, not self.no_deps)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 690, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 740, in install_item
    self.process_distribution(spec, dist, deps)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 788, in process_distribution
    distros = WorkingSet([]).resolve(
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/pkg_resources/__init__.py", line 829, in resolve
    dist = self._resolve_dist(
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/pkg_resources/__init__.py", line 865, in _resolve_dist
    dist = best[req.key] = env.best_match(
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1135, in best_match
    return self.obtain(req, installer)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/pkg_resources/__init__.py", line 1147, in obtain
    return installer(requirement)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 713, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 738, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 932, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1206, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/command/easy_install.py", line 1192, in run_setup
    run_setup(setup_script, args)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 262, in run_setup
    raise
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 169, in save_modules
    saved_exc.resume()
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 143, in resume
    raise exc.with_traceback(self._tb)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 156, in save_modules
    yield saved
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 198, in setup_context
    yield
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 259, in run_setup
    _execfile(setup_script, ns)
  File "/home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/lib/python3.8/site-packages/setuptools/sandbox.py", line 46, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-5e3d8jrf/numpy-1.26.0b1/setup.py", line 22, in <module>
    #'scikit-umfpack'
RuntimeError: Python version >= 3.9 required.
$PYTHONPATH = /tmp/tmp7imayvhxconda_skeleton_modi-flows-0.1.3.tar.gz/modi-flows-0.1.3

Leaving build/test directories:
  Work:
 /home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/work 
  Test:
 /home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/test_tmp 
Leaving build/test environments:
  Test:
source activate  /home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pl 
  Build:
source activate  /home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_build_env 


Error: command failed: /home/dtheuerkauf/anaconda3/conda-bld/skeleton_1692864953689/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeho/bin/python setup.py install
```

Considering upgrading python's req to 3.9. But before this, working on Tests.
